%%{
  init: {
    'theme': 'dark',
    'themeVariables': {
      'primaryColor': '#000000',
      'primaryTextColor': '#FFFFFF',
      'primaryBorderColor': '#7C0000',
      'lineColor': '#F8B229',
      'secondaryColor': '#006100',
      'tertiaryColor': '#fff',
      'titleColor': '#00C853',
      'darkMode': 'true',
      'mainBkg': '#000000'
    }
  }
}%%

flowchart TD
    subgraph LV-HV Progression
        A(Ball Mold)
        B(LV Circuits)
        C(MV Circuits)
        D(XP Buckets)
        E(Wafer)
        subgraph SG_QB [Questbook]
            G("Diamond Ore\n(Can't Find Those Ores?)")
            AC("Coin (The Beekeeper 1)\n(First Things First)")
            AD("Hive\n(Any Hive quest)\n(in Coins, Coins, Coins tab)")
        end
        AC --> AD
        subgraph SG_GS [Scrap]
            L(Scrap Boxes)
            M("9 Green Sapphire\n(Req. average 3.24 million trash items)")
            N(Recycler)
            O(Valid IC2 Trash Items)
            P("Packager\n(9x scrap)")
            S("IC2 Scrap\n(12.5% chance)")
            AJ(Titanium Dust)
        end
        O --> N --> S --> P --> L --> M
        L --> AJ

        F(LV+ EBF)
        H(Sifter)
        I(MV Lathe)
        F --> I
        
        J(HV Circuits)
        K(Green Sapphire Lens)
        Q(Green Sapphire Block)
        U(Green Sapphire Plate)
        V(RAM Chip)
        X(Ignis Lens)
        Y(Integrated Logic Chips)
        Z(Block of Ignis)
        subgraph SG_FS [Fire Shards]
            AA(Fire Shards)
            AB(Wizard Villager Trading)
            AS(Any Shard)
            AT(Balanced Shard Transmutation)
        end
        AB --> AS --> AT --> AA
        AB --> AA

        subgraph SG_B [Bee Start]
            AE(Get lucky and drop at least\na pristine princess + a drone)
            AF(Do all possible quests\nto get more hive trades)
            subgraph SB_BR [Renewable Ignoble Options]
                AG("Alveary Swarmer\n(MV due to Alveary)")
                AH("Hiveacynth\n(HV due to infusion)")
            end
        end
        AE --> AF
        AF --> SB_BR

        subgraph SG_SS [Stainless Steel]
            AO(Stainless Steel)
            AP(2x MV Energy Hatch EBF)
            AQ(Chrome)
            AR(Manganese)
            AU(Redstone Centrifuging)
            AV(Lava Centrifuging)
        end
        AP --> AO
        AQ --> AO
        AR --> AO
        AU --> AQ
        AV --> AR

        A --> B --> C --> J
        D -->|Gallium\nArsenic| E
        F --> E
        G --> H -->|Flawless Diamond| I
        M --> Q --> U
        U --> K
        I --> K
        E --> V
        K --> V
        V --> J
        E --> C
        Y --> J
        X --> Y
        AA --> Z
        Z --> X
        I --> X
        AD --> AE
        B --> F
    end
    subgraph SG_TI [Titanium]
        AI(Mega Blast Furnace)
        AK(Hot Titanium Ingot)
        AL("At Least 1A LuV power\n(eg 64A HV)")
        AM(Titanium Ingot)
        AN(HV Vacuum Freezer)
        AW(Implosion Compressor)
        AX(Garnet Block)
        AY(IC2 Garnydinia)
        AZ(Garnydinia Nitric Acid Processing)
        BA(Antimony)
        BB(Soldering Alloy)
        BC(864x Cupronickel Coils)
    end
    J --> AI
    AI --> AK
    AL --> AK
    AJ --> AK
    AK --> AM
    AN --> AM
    AO --> AN
    J --> AW
    AO --> AW
    AW --> AX --> AY --> AZ --> BA --> BB --> AI
    BC --> AI

    classDef gate color:#000000, fill:#00C853
    
    class A gate
    class J gate
    class AM gate
    class AO gate